package com.redhat.batigerteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CatchMessageEvent implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CatchMessageEvent() {
    }




}